// AUTH ACTIONS
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';

// MODULES ACTIONS
export const MODULE_CREATE_REQUEST = 'MODULE_CREATE_REQUEST';
export const MODULE_DELETE_REQUEST = 'MODULE_DELETE_REQUEST';
export const MODULE_UPDATE_REQUEST = 'MODULE_UPDATE_REQUEST';
export const MODULE_GET_ALL_REQUEST = 'MODULE_GET_ALL_REQUEST';
