// AUTH ACTIONS
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';

// USERS ACTIONS
export const USER_GET_ALL_REQUEST = 'USER_GET_ALL_REQUEST';
export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_SET_ERROR = 'USER_SET_ERROR';
export const USER_SET_LOADING = 'USER_SET_LOADING';

// ROLES ACTIONS
export const ROL_GET_ALL_REQUEST = 'ROL_GET_ALL_REQUEST';

// SCOPES ACTIONS
export const SCOPE_GET_ALL_REQUEST = 'SCOPES_GET_ALL_REQUEST';

// MODULES ACTIONS
export const MODULE_CREATE_REQUEST = 'MODULE_CREATE_REQUEST';
export const MODULE_DELETE_REQUEST = 'MODULE_DELETE_REQUEST';
export const MODULE_UPDATE_REQUEST = 'MODULE_UPDATE_REQUEST';
export const MODULE_GET_ALL_REQUEST = 'MODULE_GET_ALL_REQUEST';

// DB LP ACTIONS
export const LPUSER_GET_REQUEST = 'LPUSER_GET_REQUEST';
export const LPUSER_LOADING_REQUEST = 'LPUSER_LOADING_REQUEST';

